// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQhcEBfRL09VGr6t4HCDpgKhD-EIsKRqM',
    appId: '1:1033350640648:web:68d7f2a3967d69c9a5cdbd',
    messagingSenderId: '1033350640648',
    projectId: 'breedit-74eef',
    authDomain: 'breedit-74eef.firebaseapp.com',
    storageBucket: 'breedit-74eef.firebasestorage.app',
    measurementId: 'G-7JEH5BVNVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzu2ezFLR2DvffXsIqQqvU2F2U-k3mkgU',
    appId: '1:1033350640648:android:37690e6745a8a7a5a5cdbd',
    messagingSenderId: '1033350640648',
    projectId: 'breedit-74eef',
    storageBucket: 'breedit-74eef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApB3mV9M_lN6MRP92Y_SGUFaQsIuwzvo4',
    appId: '1:1033350640648:ios:3a98b7782d8dd4c8a5cdbd',
    messagingSenderId: '1033350640648',
    projectId: 'breedit-74eef',
    storageBucket: 'breedit-74eef.firebasestorage.app',
    iosBundleId: 'com.example.breedit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApB3mV9M_lN6MRP92Y_SGUFaQsIuwzvo4',
    appId: '1:1033350640648:ios:3a98b7782d8dd4c8a5cdbd',
    messagingSenderId: '1033350640648',
    projectId: 'breedit-74eef',
    storageBucket: 'breedit-74eef.firebasestorage.app',
    iosBundleId: 'com.example.breedit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQhcEBfRL09VGr6t4HCDpgKhD-EIsKRqM',
    appId: '1:1033350640648:web:64ca39b2ffc304bda5cdbd',
    messagingSenderId: '1033350640648',
    projectId: 'breedit-74eef',
    authDomain: 'breedit-74eef.firebaseapp.com',
    storageBucket: 'breedit-74eef.firebasestorage.app',
    measurementId: 'G-RTB06BDR49',
  );
}
