// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvCMYmwmZ1MGFP0UdVVbUxSf6AD2Zt4io',
    appId: '1:417213841022:web:c8304fe0dfcb849645622f',
    messagingSenderId: '417213841022',
    projectId: 'breedit-36cb7',
    authDomain: 'breedit-36cb7.firebaseapp.com',
    storageBucket: 'breedit-36cb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN6bBjEwFQoUOpeDlOBMpBjHG13qoTsMY',
    appId: '1:417213841022:android:fee61a388b7a3ec745622f',
    messagingSenderId: '417213841022',
    projectId: 'breedit-36cb7',
    storageBucket: 'breedit-36cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5PG8EEK9JEMzJ_qBedu8E3tP0-8pRlmM',
    appId: '1:417213841022:ios:6cc1f050a995545445622f',
    messagingSenderId: '417213841022',
    projectId: 'breedit-36cb7',
    storageBucket: 'breedit-36cb7.appspot.com',
    iosBundleId: 'com.example.breedit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5PG8EEK9JEMzJ_qBedu8E3tP0-8pRlmM',
    appId: '1:417213841022:ios:6cc1f050a995545445622f',
    messagingSenderId: '417213841022',
    projectId: 'breedit-36cb7',
    storageBucket: 'breedit-36cb7.appspot.com',
    iosBundleId: 'com.example.breedit',
  );
}
