// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEpSgOjAV0yl9OQzjQmznZI6cTw_sinMQ',
    appId: '1:307114636792:web:7ded3b6a8a83e7a61b920d',
    messagingSenderId: '307114636792',
    projectId: 'breedit-81cfe',
    authDomain: 'breedit-81cfe.firebaseapp.com',
    storageBucket: 'breedit-81cfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFgPt37DJfQ83X4dGTRynZ74xjFKDUKKs',
    appId: '1:307114636792:android:e2b9e197cd003a171b920d',
    messagingSenderId: '307114636792',
    projectId: 'breedit-81cfe',
    storageBucket: 'breedit-81cfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU8Wp_9L3A2pEtQKkDTpgYP0srPWKf0iA',
    appId: '1:307114636792:ios:2d851291310cc9d81b920d',
    messagingSenderId: '307114636792',
    projectId: 'breedit-81cfe',
    storageBucket: 'breedit-81cfe.appspot.com',
    iosBundleId: 'com.example.breedit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU8Wp_9L3A2pEtQKkDTpgYP0srPWKf0iA',
    appId: '1:307114636792:ios:2d851291310cc9d81b920d',
    messagingSenderId: '307114636792',
    projectId: 'breedit-81cfe',
    storageBucket: 'breedit-81cfe.appspot.com',
    iosBundleId: 'com.example.breedit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEpSgOjAV0yl9OQzjQmznZI6cTw_sinMQ',
    appId: '1:307114636792:web:c80584bf15f6dd2c1b920d',
    messagingSenderId: '307114636792',
    projectId: 'breedit-81cfe',
    authDomain: 'breedit-81cfe.firebaseapp.com',
    storageBucket: 'breedit-81cfe.appspot.com',
  );

}